# TimeSeriesDataLoader Configuration

# Data loading settings
duration_days: 365                # Number of days of historical data to load
start_date: "2021-08-01"         # Optional: Start date in YYYY-MM-DD format
end_date: "2022-12-31"           # Optional: End date in YYYY-MM-DD format
aggregation: TIME                 # Aggregation type (TIME, NONE, etc.)
aggregation_function: MEAN        # Aggregation function (MEAN, MAX, MIN, etc.)
read_type: RAW                    # Read type for Aspen historian (RAW, INTERPOLATED, etc.)

# CSV-specific settings
csv_path: data/tags_data.csv     # Path to CSV file
time_column: timestamp           # Column name containing timestamps

# Tags to retrieve
tags:
  - NP01-B4TES2L0
  - NP01-B4TES2L0_380
  - NP01-B4TES2L0_480
  - NP01-B4TES2L1
  - NP01-B4TES2L1_0
  - NP01-B4TES2L1_460
  - NP01-B4TES2L1_560
  - NP01-B4TES2L2
  - NP01-B4TES2L2_460
  - NP01-B4TES2L2_560
